#ifndef INC_XPT2046PERIPHERALMAPPING_H_
#define INC_XPT2046PERIPHERALMAPPING_H_

#define 	TOUCH_SPI_MODULE 	SPI2

#define 	TOUCH_CS_PORT 		GPIOB
#define 	TOUCH_CS_PIN  		GPIO_BSRR_BS3

#define 	TOUCH_PEN_PORT		GPIOB
#define 	TOUCH_PEN_PIN		GPIO_IDR_IDR4

#endif