#ifndef INC_ILI9341PERIPHERALMAPPING_H_
#define INC_ILI9341PERIPHERALMAPPING_H_

#define 	LCD_SPI_MODULE 	SPI2
#define 	LCD_CS_PORT 	GPIOA
#define 	LCD_CS_PIN  	GPIO_BSRR_BS15
#define 	LCD_DC_PORT 	GPIOA
#define 	LCD_DC_PIN 		GPIO_BSRR_BS12
#define 	LCD_RST_PORT	GPIOA
#define 	LCD_RST_PIN		GPIO_BSRR_BS11

#endif /*INC_ILI9341PERIPHERALMAPPING_H_*/
